### PR TITLE
Add an option to disable rebasing of relativeTo

### PR DESCRIPTION
**Pull request by XrXr**
Implement #12

### CODE REVIEW

**Comment by XrXr** [comment]
appveyor failed because it couldn't run the tests...

**Comment by shinnn** [comment]
https://github.com/shinnn/broccoli-clean-css/pull/1#issuecomment-56367481

@kanongil says:

> Anyway, I didn't really add options but rather fix the handling of the existing ones.

**Comment by XrXr** [comment]
That pull request did solve the fact that there was no way to import from the input tree, but it made it so that it's impossible to import relative to the current working directory.

I don't see how we can keep both behaviours without adding an option

**Comment by XrXr** [comment]
@shinnn Any update on this? Would like to hear more thoughts from you.

**Comment by XrXr** [comment]
See #12

**Pull request closed without merging**
